"""Public immutable handoff contract for the Viola two-PC workflow."""

from .contract import (
    CONTRACT_SHA256,
    DEFAULT_ACCEPT_ROOT,
    DEFAULT_HANDOFF_ROOT,
    KIND_RULES,
    SCHEMA_VERSION,
    SUPPORTED_KINDS,
    RuntimeIdentity,
    SealRequest,
    VerifiedBundle,
    accept_bundle,
    ack_bundle,
    canonical_json_bytes,
    copy_paste_message,
    inspect_bundle,
    inventory_root,
    require_active_canonical_source,
    resolve_bundle,
    seal_bundle,
    seal_validated_rollout_session_bundle,
    verify_bundle,
    wandb_run_id,
)
from .errors import BundleValidationError, EnvironmentValidationError, EvidenceError, HandoffError
from .evidence import EvidenceLogger, WandbEvidenceLogger

__all__ = [
    "CONTRACT_SHA256",
    "DEFAULT_ACCEPT_ROOT",
    "DEFAULT_HANDOFF_ROOT",
    "KIND_RULES",
    "SCHEMA_VERSION",
    "SUPPORTED_KINDS",
    "BundleValidationError",
    "EnvironmentValidationError",
    "EvidenceError",
    "EvidenceLogger",
    "HandoffError",
    "RuntimeIdentity",
    "SealRequest",
    "VerifiedBundle",
    "WandbEvidenceLogger",
    "accept_bundle",
    "ack_bundle",
    "canonical_json_bytes",
    "copy_paste_message",
    "inspect_bundle",
    "inventory_root",
    "require_active_canonical_source",
    "resolve_bundle",
    "seal_bundle",
    "seal_validated_rollout_session_bundle",
    "verify_bundle",
    "wandb_run_id",
]
